apiVersion: v1
kind: Service
metadata:
  name: happy-paws-backend-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: happy-paws-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30008
