apiVersion: apps/v1
kind: Deployment
metadata:
  name: happy-paws-backend
  namespace: default
  labels:
    app: happy-paws-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: happy-paws-backend
  template:
    metadata:
      labels:
        app: happy-paws-backend
    spec:
      containers:
      - name: happy-paws-backend
        image: reisende8/happy-paws-backend:latest
        ports:
        - containerPort: 80
